matrix:
  include:
   - language: c
     sudo: required
     env: 
     - SIMINT_EXTRA=-DBUILD_SHARED_LIBS:Bool=True
     - BUILD_SHARED_LIB=true
     - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/simint/lib/:$PWD/lib/
   - language: c
     sudo: required
   - language: c
     sudo: required
     env:
     - VALENCE_EXTRA_FLAGS="-O0 -fprofile-arcs -ftest-coverage"

before_install:
  - sudo apt-get install -y gfortran cmake
  - ./install-simint.sh
  - ./install-mpich.sh
script:
  - make
  - make test
  - export PATH=/home/travis/bin/:$PATH
  - export LD_LIBRARY_PATH=/home/travis/lib:/$LD_LIBRARY_PATH
  - SEQUENTIAL=false make
  - SEQUENTIAL=false travis_wait 120 make test-large
after_success:
  - bash <(curl -s https://codecov.io/bash)