language: C
sudo: required
before_install:
  - sudo apt-get install -y gfortran cmake
  - ./install-simint.sh
  - ./install-mpich.sh
script: 
  - make
  - make test
  - export PATH=/home/travis/bin/:$PATH
  - export LD_LIBRARY_PATH=/home/travis/lib:/$LD_LIBRARY_PATH
  - SEQUENTIAL=false make
  - SEQUENTIAL=false travis_wait 60 make test-large
