#!/bin/bash
#
#  This is an example bash script to run each test case in the "examples" array below
#  and compare the output to the correct output in testing.py
#  Usage:
#
#  ./test_script executable
#
#  This assumes you're running from the base valence directory.
#

examples=(li li- lih lih-sv li_opt h h+ndf he h2-sz h2-dz \
    h2o-vdz-sc1 b be-sv be be+ndf be-sc he3s-1s3s he1s2s be3s2 be-scv3s+2sc )

# check number of arguments
if [ "$#" -ne 1 ]; then
    echo "Need one input--the name of the executable to test"
    exit
fi

datestamp=`date +%d%b%Y_%H%M%S`
SECONDS=0
# check if $1 exists and is executable
  if [[ -x "$1" ]]
  then
      cd testing
      echo "Running tests in" $(PWD) on $(uname -a) | tee -a testing.log
      for i in ${examples[@]}
      do
          OUTPUT=$i_$datestamp.out
          $1 < test_cases/$i > $OUTPUT
          python testing.py $OUTPUT $i | tee -a testing.log
      done
      echo Tests completed in $SECONDS seconds on $(date) | tee -a testing.log
      echo ----------------------------------------------------------------------\n >> testing.log
      cd ..
  else
      echo "Input file '$1' is not executable or found."
      echo "Couldn't find/execute it after looking with"
      echo "`pwd` as the base directory."
  fi
