#!/bin/bash
#
#  This is an example bash script to run each test case in the "examples" array below
#  and compare the output to the correct output in testing.py
#  Usage:
#
#  ./test_script executable
#
#  This assumes you're running from the base valence directory.
#

  examples=(li li- lih lih-sv li_opt h h+ndf he h2-sz h2-dz h2o-vdz-sc1 h2o-vdz \
      h2o-vdz-dem cu+ b be-sv be be+ndf ethane ethane2 be-sc he3s-1s3s he1s2s \
      be3s2 be-scv3s+2sc f2-scval-p2 n2.sc4val-b.p2 c2-pt-vshf-p2)

  NCORE=$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
  echo Using $NCORE ranks...
# check number of arguments
if [ "$#" -ne 1 ]; then
    echo "Need one input--the name of the executable to test"
    exit
fi

# check if $1 exists and is executable
  if [[ -x "$1" ]]
  then
      for i in ${examples[@]}
      do
          mpirun -n $NCORE $1 < ./testing/test_cases/$i > $i.out
          python ./testing/testing.py $i.out $i
      done
  else
      echo "Input file '$1' is not executable or found."
      echo "Couldn't find/execute it after looking with"
      echo "`pwd` as the base directory."
  fi
